const dataUri: (path: string) => string = require('data-uri.macro');

const options = {
    "Soyjack": dataUri("../img/soyjack.jpeg"),
    "Soyjack2": dataUri("../img/soyjack2.png"),
    "Soyjack3": dataUri("../img/soyjack3.jpeg"),
    "Soyjack4": dataUri("../img/soyjack4.png"),
    "Soyjack5": dataUri("../img/soyjack5.jpeg"),
    "Soyjack6": dataUri("../img/soyjack6.jpeg"),
    "Soyjack7": dataUri("../img/soyjack7.png"),
    "Soyjack8": dataUri("../img/soyjack8.png"),
    "Soyjack9": dataUri("../img/soyjack9.jpeg"),
    "Soyjack10": dataUri("../img/soyjack10.png"),
    "ChadWojak": dataUri("../img/chadwojak.png"),
    "Gigachad": dataUri("../img/gigachad.jpeg"),
    "Gigachad2": dataUri("../img/gigachad2.jpeg"),
    "PointingFingers": dataUri("../img/pointingfingers.png"),
    "Pink": dataUri("../img/pink.png"),
    "Grace": dataUri("../img/grace.png"),
    "Doomer": dataUri("../img/doomer.jpeg"),
    "PorkyCrying": dataUri("../img/porkycrying.png"),
    "PorkySoy": dataUri("../img/porkysoy.png"),
    "PorkyScared": dataUri("../img/porkyscared.png"),
    "PorkyMad": dataUri("../img/porkymad.png"),
    "PorkyNPC": dataUri("../img/porkynpc.png"),
    "Marx": dataUri("../img/marx.jpeg"),
    "Lenin": dataUri("../img/lenin.png"),
    "Trotsky": dataUri("../img/trotsky.png"),
    "Putin": dataUri("../img/putin.jpeg"),
    "Jannie": dataUri("../img/jannie.png"),
    "Jannie2": dataUri("../img/jannie2.png"),
    "4cuck": dataUri("../img/4cuck.png"),
    "/pol/cel": dataUri("../img/polcel.png"),
    "/pol/cel2": dataUri("../img/polcel2.png"),
    "/pol/cel3": dataUri("../img/polcel3.png"),
    "/pol/cel4": dataUri("../img/polcel4.png"),
    "Plebbit": dataUri("../img/plebbit.jpeg"),
    "BasedPepe": dataUri("../img/basedpepe.jpeg"),
    "Pajeet": dataUri("../img/pajeet.png"),
    "Mutt": dataUri("../img/mutt.png"),
    "Mutt2": dataUri("../img/mutt2.png"),
    "Mutt3": dataUri("../img/mutt3.png"),
    "Lincuck": dataUri("../img/lincuck.png"),
    "Soymer": dataUri("../img/soymer.png"),
    "Pseud": dataUri("../img/pseud.jpeg"),
    "Fed": dataUri("../img/fed.png"),
    "NPCBrainlet": dataUri("../img/npcbrainlet.jpeg"),
    "SoyNPC": dataUri("../img/soynpc.png"),
    "Hitler": dataUri("../img/hitler.jpeg"),
    "Nazi": dataUri("../img/nazi.png"),
    "Nazi2": dataUri("../img/nazi2.png"),
    "Jew": dataUri("../img/jew.jpeg"),
    "Brainlet": dataUri("../img/brainlet.jpeg"),
    "Brainlet2": dataUri("../img/brainlet2.jpeg")
}

export default options